# Generated by Django 4.1 on 2022-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='Conan', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='smash', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='The barbarian', max_length=100),
        ),
    ]
