# Generated by Django 4.1 on 2022-08-09 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='published_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
