# Generated by Django 4.1 on 2022-08-10 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_employee_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Motive')),
                ('start_date', models.DateTimeField(default=datetime.date.today, verbose_name='Date: initial')),
                ('end_date', models.DateTimeField(default=datetime.date.today, verbose_name='Date: initial')),
            ],
        ),
    ]
