# Generated by Django 4.1 on 2022-08-10 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descriptions'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
