# Generated by Django 4.1 on 2022-08-11 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_jobs_description_jobs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='end_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Ended at:'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Started at:'),
        ),
    ]
