# Generated by Django 4.1 on 2022-08-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_jobs_date_alter_jobs_end_date_alter_jobs_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='elapsed',
            field=models.TimeField(null=True),
        ),
    ]
