# Generated by Django 4.1 on 2022-08-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_jobs_elapsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='elapsed',
        ),
    ]
