# Generated by Django 4.1 on 2022-08-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_jobs_elapsed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
